# Generated by Django 5.2.7 on 2026-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.AddField(
            model_name='project',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='apks/'),
        ),
    ]
