# Generated by Django 5.2.7 on 2026-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_live_url_project_apk_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='apk_url',
            field=models.URLField(blank=True, help_text='Paste the Google Drive direct link here to bypass Vercel/Cloudinary size limits.', null=True, verbose_name='Direct APK Download URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='v1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('tools', 'Tools')], default='backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(default='fab fa-python', help_text="FontAwesome class e.g., 'fab fa-flutter'", max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=80, help_text='Enter a value from 0 to 100'),
        ),
    ]
